### PR TITLE
add pyproject.toml

### PR DESCRIPTION
**Pull request by eth3lbert**
- Add pyproject.toml and support for setuptools-rust (#5)

### CODE REVIEW

**Comment by lilydjwg** [comment]
Something goes wrong. The `luoxu` and `luoxu_plugins` packages are not included in the built result.

**Comment by eth3lbert** [comment]
Could you briefly describe the installation and build process?

**Comment by lilydjwg** [comment]
I ran `python -m build --wheel` and inspected the `dist/....whl` file.

**Comment by eth3lbert** [comment]
@lilydjwg nicely ping
new commit should include both packages now.

**Comment by lilydjwg** [comment]
It works, thanks!

**Pull request merged**
